#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
TSE-ASR End-to-End Training Script (supports single-GPU and multi-GPU DDP)

Training workflow: audio -> TSE model -> Loss backpropagation to optimize TSE

Supported loss_mode (specified in YAML config via loss_mode):
  - ce         : ASR transcription CE Loss only (Whisper teacher-forcing)
  - similarity : Speaker similarity Ranking Loss only
                 Requires sim(tse_out, enroll) > sim(mix, enroll) + margin
  - combined   : Weighted sum of CE Loss + similarity Ranking Loss + target speaker VAD Loss
                 total = lambda_ce * ce_loss + lambda_sim * sim_loss + lambda_vad * vad_loss

Key config fields (YAML):
  loss_mode   : "ce" | "similarity" | "combined"   (default "combined")
  lambda_ce   : CE loss weight                      (default 1.0)
  lambda_sim  : Similarity loss weight              (default 0.5)
  lambda_vad  : Target speaker VAD loss weight      (default 0.5)
  sim_margin  : ranking margin                      (default 0.2)
  vad_frame_shift_ms : VAD frame shift (ms)         (default 10)
  spk_encoder_path : Speaker encoder model dir or weights (required for similarity/combined)

Single GPU:
    python train.py --config configs/config_bsrnn_ecapa_vox1.yaml
Multi-GPU (torchrun):
    torchrun --nproc_per_node=4 train.py --config configs/config_bsrnn_ecapa_vox1.yaml
"""

import argparse
import json
import os
import sys
import logging
import random
import shutil
import time
import datetime
import shlex
import subprocess
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.distributed as dist
import torchaudio
import yaml
from torch.utils.data import Dataset, DataLoader
from torch.utils.data.distributed import DistributedSampler
from torch.utils.tensorboard import SummaryWriter
from tqdm import tqdm

from resume_utils import resolve_resume_epoch

# ── wesep TSE model path ────────────────────────────────────────────────────
# Add wesep_real_tse to sys.path, using wesep from REAL-TSE-Challenge
_SCRIPT_DIR = Path(__file__).resolve().parent
_WESEP_PATH = _SCRIPT_DIR.parent / "REAL-TSE-Challenge" / "wesep_real_tse"
if str(_WESEP_PATH) not in sys.path:
    sys.path.insert(0, str(_WESEP_PATH))

# Note: Whisper ASR is loaded via HuggingFace transformers, no need to inject openai-whisper path

# ===========================================================================
# Differentiable DNSMOS Loss (self-contained, loads pre-converted .pt models via torch.load)
# No dependency on onnx2torch / wesep / numba, only requires torch + torchaudio + librosa
# ===========================================================================

def _poly1d_torch(coefficients, x: torch.Tensor) -> torch.Tensor:
    result = torch.zeros_like(x)
    for c in coefficients:
        result = result * x + c
    return result


def _dnsmos_polyfit(sig: torch.Tensor, bak: torch.Tensor, ovr: torch.Tensor):
    """Mirror dnsmos_local._get_polyfit_val (non-personalized)"""
    sig_out = _poly1d_torch([-0.08397278, 1.22083953,  0.0052439],   sig)
    bak_out = _poly1d_torch([-0.13166888, 1.60915514, -0.39604546],  bak)
    ovr_out = _poly1d_torch([-0.06766283, 1.11546468,  0.04602535],  ovr)
    return sig_out, bak_out, ovr_out


class DNSMOSLoss(nn.Module):
    """Differentiable DNSMOS Loss — loads pre-converted .pt models directly, no onnx2torch/wesep/numba dependency.

    Usage:
        loss_fn = DNSMOSLoss(primary_pt, p808_pt, target_metric="OVRL")
        loss = loss_fn(inf=tse_out).mean()   # ref is optional, not used in computation

    .pt files are generated by DNSMOS/convert_onnx_to_pt.py.
    """

    _SR = 16000
    _INPUT_LEN = 9.01  # Consistent with Microsoft DNS-Challenge (seconds)

    def __init__(
        self,
        primary_model_path: str,
        p808_model_path: str,
        target_metric: str = "OVRL",
    ):
        super().__init__()
        assert target_metric in ("OVRL", "SIG", "BAK", "P808"), (
            f"target_metric 必须是 OVRL/SIG/BAK/P808，得到 {target_metric!r}"
        )
        self.target_metric = target_metric
        self._len_samples = int(self._INPUT_LEN * self._SR)

        # 加载预转换的 PyTorch 模型（torch.save 保存的完整模型对象）
        self.primary_model = torch.load(primary_model_path, weights_only=False)
        self.primary_model.eval()
        self.p808_model = torch.load(p808_model_path, weights_only=False)
        self.p808_model.eval()

        self._spectrogram = torchaudio.transforms.Spectrogram(
            n_fft=321, hop_length=160, pad_mode="constant"
        )
        self._to_db = torchaudio.transforms.AmplitudeToDB("power", top_db=80.0)

    def _melspec(self, audio: torch.Tensor) -> torch.Tensor:
        """audio: (T,) → mel (T', 120)"""
        import librosa
        import math
        fb = torch.as_tensor(
            librosa.filters.mel(sr=self._SR, n_fft=321, n_mels=120).T,
            dtype=audio.dtype, device=audio.device,
        )
        spec = self._spectrogram.to(audio.device)(audio.unsqueeze(0)).squeeze(0)  # (161, T')
        mel = torch.matmul(spec.transpose(0, 1), fb)                               # (T', 120)
        self._to_db.db_multiplier = math.log10(
            max(self._to_db.amin, float(mel.max()))
        )
        mel_db = (self._to_db(mel.transpose(0, 1)).transpose(0, 1) + 40.0) / 40.0
        return mel_db

    def _score_one(self, audio: torch.Tensor) -> torch.Tensor:
        """audio: (T,) → scalar DNSMOS score（可微分）"""
        import math
        # 短音频重复填充到至少 9.01s
        while audio.shape[0] < self._len_samples:
            audio = torch.cat([audio, audio], dim=0)

        num_hops = int(math.floor(audio.shape[0] / self._SR) - self._INPUT_LEN) + 1
        hop = self._SR
        scores: List[torch.Tensor] = []

        pm = self.primary_model.to(audio.device)
        p8 = self.p808_model.to(audio.device)

        for idx in range(num_hops):
            seg = audio[int(idx * hop): int((idx + self._INPUT_LEN) * hop)]
            if seg.shape[0] < self._len_samples:
                continue
            inp = seg.float().unsqueeze(0)              # (1, T)
            raw = pm(inp)[0]
            if raw.dim() == 2:
                raw = raw[0]
            sig_r, bak_r, ovr_r = raw[0], raw[1], raw[2]
            sig, bak, ovr = _dnsmos_polyfit(sig_r, bak_r, ovr_r)

            if self.target_metric == "P808":
                mel = self._melspec(seg[:-160])
                p808_score = p8(mel.float().unsqueeze(0))
                if p808_score.dim() > 1:
                    p808_score = p808_score.squeeze()
                scores.append(p808_score)
            else:
                scores.append({"SIG": sig, "BAK": bak, "OVRL": ovr}[self.target_metric])

        if not scores:
            return torch.zeros(1, device=audio.device, requires_grad=True).squeeze()
        return torch.stack(scores).mean()

    def forward(self, inf: torch.Tensor, ref: Optional[torch.Tensor] = None) -> torch.Tensor:
        """
        inf: (B, T)  TSE 输出（ref 不参与计算，可不传）
        返回: (B,) 负 DNSMOS 分数（minimize = maximize DNSMOS）
        """
        if inf.dim() == 3:
            inf = inf[:, 0, :]
        losses: List[torch.Tensor] = []
        for i in range(inf.shape[0]):
            losses.append(-self._score_one(inf[i]))
        return torch.stack(losses)


_DNSMOS_LOSS_AVAILABLE = True   # 自包含实现，无外部依赖


# ===========================================================================
# 数据集
# ===========================================================================

# 数据集语言映射（每个数据集的音频语言）
DATASET_LANG: Dict[str, str] = {
    "CHiME6":    "en",
    "AMI":       "en",
    "DipCo":     "en",
    "AliMeeting": "zh",
    "AISHELL-4": "zh",
}


class TSEASRDataset(Dataset):
    """
    TSE-ASR 训练数据集

    每个样本包含:
      - mixture_wav:  混合音频 (多说话人)，Tensor [T]
      - enroll_wav:   目标说话人注册音频，Tensor [T_e]
      - transcript:   目标说话人转录文本，str
      - language:     音频语言，'zh' 或 'en'

    数据来源: 4 个数据集，每个数据集包含:
      - mapping.csv:   utterance -> wav 路径
      - TRAIN/*_meta.csv: mixture_utterance, enrolment_speakers_utterance, transcript

    支持通过 train_roots（列表）指定多个数据根目录（如原始数据 + 增强数据），
    各根目录使用相同的 datasets 和 dataset_subdirs 配置，数据会合并加载。
    也可单独指定 aug_data 作为唯一根目录。
    """

    def __init__(
        self,
        train_roots: List[str],
        datasets: List[str],
        dataset_subdirs: Dict[str, str],
        sample_rate: int = 16000,
        max_mix_len: int = 480000,
        max_enroll_len: int = 160000,
        min_transcript_len: int = 2,
        max_samples: int = 0,
        load_vad_labels: bool = True,
    ):
        super().__init__()
        self.sample_rate = sample_rate
        self.max_mix_len = max_mix_len
        self.max_enroll_len = max_enroll_len
        self.min_transcript_len = min_transcript_len
        self.load_vad_labels = load_vad_labels

        self.samples = []  # List of (mix_path, enroll_path, transcript, language, vad_segments)
        for root in train_roots:
            before = len(self.samples)
            self._load_data(root, datasets, dataset_subdirs)
            added = len(self.samples) - before
            logging.info(f"[Dataset] 数据根目录 {root} 新增 {added} 条样本")

        if max_samples > 0:
            self.samples = self.samples[:max_samples]

        logging.info(f"[Dataset] 共加载 {len(self.samples)} 条样本")

    def _load_vad_index(
        self,
        train_root: str,
        datasets: List[str],
        dataset_subdirs: Dict[str, str],
    ) -> Dict[str, List[List[float]]]:
        """
        加载所有数据集的 target_activity_segments.jsonl，建立
        (mixture_utterance, speaker) -> segments 的索引。
        """
        dataset_key_map = {
            "CHiME6":     "chime6_subdir",
            "AMI":        "ami_subdir",
            "AliMeeting":  "alimeeting_subdir",
            "AISHELL-4":  "aishell4_subdir",
        }
        vad_index: Dict[str, List[List[float]]] = {}
        for ds_name in datasets:
            subdir_key = dataset_key_map.get(ds_name)
            if subdir_key is None:
                continue
            subdir = dataset_subdirs.get(subdir_key, ds_name)
            vad_file = Path(train_root) / subdir / "TRAIN" / "target_activity_segments.jsonl"
            if not vad_file.exists():
                logging.warning(f"[Dataset] VAD 标签文件不存在: {vad_file}")
                continue
            cnt = 0
            with open(vad_file, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    rec = json.loads(line)
                    key = (rec["mixture_utterance"], rec["speaker"])
                    vad_index[key] = rec["segments"]
                    cnt += 1
            logging.info(f"[Dataset] VAD 标签: {ds_name} 加载 {cnt} 条")
        return vad_index

    def _load_data(
        self,
        train_root: str,
        datasets: List[str],
        dataset_subdirs: Dict[str, str],
    ):
        """从各数据集的 mapping.csv + meta.csv 中加载样本"""
        dataset_key_map = {
            "CHiME6":     "chime6_subdir",
            "AMI":        "ami_subdir",
            "AliMeeting":  "alimeeting_subdir",
            "AISHELL-4":  "aishell4_subdir",
        }
        meta_file_map = {
            "CHiME6":     "CHiME6_meta.csv",
            "AMI":        "AMI_meta.csv",
            "AliMeeting":  "AliMeeting_meta.csv",
            "AISHELL-4":  "AISHELL-4_meta.csv",
        }

        # 加载 VAD 标签索引
        vad_index: Dict[str, List[List[float]]] = {}
        if self.load_vad_labels:
            vad_index = self._load_vad_index(train_root, datasets, dataset_subdirs)

        for ds_name in datasets:
            subdir_key = dataset_key_map.get(ds_name)
            if subdir_key is None:
                logging.warning(f"[Dataset] 未知数据集名 {ds_name}，跳过")
                continue

            subdir = dataset_subdirs.get(subdir_key, ds_name)
            ds_root = Path(train_root) / subdir

            mapping_csv = ds_root / "mapping.csv"
            meta_csv    = ds_root / "TRAIN" / meta_file_map[ds_name]

            if not mapping_csv.exists():
                logging.warning(f"[Dataset] mapping.csv 不存在: {mapping_csv}，跳过")
                continue
            if not meta_csv.exists():
                logging.warning(f"[Dataset] meta.csv 不存在: {meta_csv}，跳过")
                continue

            # 加载路径映射（仅包含 mixture 音频）
            mapping_df = pd.read_csv(mapping_csv)
            utterance_map: Dict[str, str] = (
                mapping_df.set_index("utterance")["path"].to_dict()
            )

            # 注册音频目录：enrolment_speakers/{utterance}.wav
            enroll_dir = ds_root / "enrolment_speakers"

            # 加载 meta
            meta_df = pd.read_csv(meta_csv)

            ds_lang = DATASET_LANG.get(ds_name)  # 该数据集的语言
            if ds_lang is None:
                logging.warning(
                    f"[Dataset] 数据集 {ds_name} 未在 DATASET_LANG 中配置语言，"
                    f"跳过该数据集（请在 DATASET_LANG 中添加对应语言映射）"
                )
                continue
            cnt_ok = cnt_skip = 0
            for _, row in meta_df.iterrows():
                mix_utt    = row["mixture_utterance"]
                enroll_utt = row["enrolment_speakers_utterance"]
                speaker    = row.get("speaker", "")
                # 列名可能是 "transcript" 或 "ground_truth_transcript"
                transcript = str(
                    row.get("transcript", row.get("ground_truth_transcript", ""))
                ).strip()

                # 过滤短文本
                if len(transcript) < self.min_transcript_len:
                    cnt_skip += 1
                    continue

                mix_path = utterance_map.get(mix_utt)

                # 注册音频：优先从 mapping.csv 查，找不到则直接拼接目录路径
                enroll_path = utterance_map.get(enroll_utt)
                if enroll_path is None:
                    candidate = enroll_dir / (enroll_utt + ".wav")
                    if candidate.exists():
                        enroll_path = str(candidate)

                if mix_path is None or enroll_path is None:
                    cnt_skip += 1
                    continue

                # 获取 VAD segments（可能为 None，训练时跳过 VAD loss）
                vad_segments = vad_index.get((mix_utt, speaker), None)

                self.samples.append((mix_path, enroll_path, transcript, ds_lang, vad_segments))
                cnt_ok += 1

            logging.info(
                f"[Dataset] {ds_name}: 加载 {cnt_ok} 条，跳过 {cnt_skip} 条"
            )

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> Optional[Dict]:
        mix_path, enroll_path, transcript, language, vad_segments = self.samples[idx]

        try:
            mix_wav,    sr_m = torchaudio.load(mix_path)
            enroll_wav, sr_e = torchaudio.load(enroll_path)
        except Exception as e:
            logging.warning(f"[Dataset] 音频加载失败 idx={idx}: {e}")
            return None

        # 转换采样率
        if sr_m != self.sample_rate:
            mix_wav = torchaudio.functional.resample(mix_wav, sr_m, self.sample_rate)
        if sr_e != self.sample_rate:
            enroll_wav = torchaudio.functional.resample(enroll_wav, sr_e, self.sample_rate)

        # 单声道
        if mix_wav.shape[0] > 1:
            mix_wav = mix_wav.mean(0, keepdim=True)
        if enroll_wav.shape[0] > 1:
            enroll_wav = enroll_wav.mean(0, keepdim=True)

        mix_wav    = mix_wav.squeeze(0)      # [T]
        enroll_wav = enroll_wav.squeeze(0)   # [T_e]

        # 过滤超长 mixture
        if self.max_mix_len > 0 and mix_wav.shape[0] > self.max_mix_len:
            return None

        # 截断过长的 enrollment
        if self.max_enroll_len > 0 and enroll_wav.shape[0] > self.max_enroll_len:
            enroll_wav = enroll_wav[: self.max_enroll_len]

        return {
            "mixture":      mix_wav,        # [T]
            "enroll":       enroll_wav,     # [T_e]
            "transcript":   transcript,     # str
            "language":     language,       # 'zh' 或 'en'
            "vad_segments": vad_segments,   # List[[start, end]] 或 None
        }


def tse_asr_collate_fn(batch: List) -> Optional[Dict]:
    """
    对齐并组装 batch，过滤掉 None 样本。
    返回:
        mixture:  [B, T_max]  (zero-padded)
        enroll:   [B, T_e_max]
        mix_lens: [B]  实际长度（采样点数）
        transcripts: List[str]
        languages:   List[str]  每条样本的语言 ('zh'/'en')
        vad_segments: List[Optional[List[[start, end]]]]  目标说话人 VAD 标签
    """
    batch = [b for b in batch if b is not None]
    if len(batch) == 0:
        return None

    mix_wavs      = [b["mixture"]    for b in batch]
    enroll_wavs   = [b["enroll"]     for b in batch]
    transcripts   = [b["transcript"] for b in batch]
    languages     = [b["language"] for b in batch]   # 每条样本必须有 language 字段
    vad_segments  = [b.get("vad_segments", None) for b in batch]

    mix_lens    = torch.tensor([w.shape[0] for w in mix_wavs], dtype=torch.long)
    enroll_lens = torch.tensor([w.shape[0] for w in enroll_wavs], dtype=torch.long)

    mixture = torch.nn.utils.rnn.pad_sequence(mix_wavs,    batch_first=True)
    enroll  = torch.nn.utils.rnn.pad_sequence(enroll_wavs, batch_first=True)

    return {
        "mixture":      mixture,       # [B, T_max]
        "enroll":       enroll,        # [B, T_e_max]
        "mix_lens":     mix_lens,      # [B]
        "enroll_lens":  enroll_lens,   # [B]
        "transcripts":  transcripts,   # List[str]
        "languages":    languages,     # List[str]，每条样本的语言
        "vad_segments": vad_segments,  # List[Optional[List[[start,end]]]]
    }


# ===========================================================================
# TSE 模型加载
# ===========================================================================

def build_tse_model(cfg: Dict, pretrained_path: Optional[str] = None) -> nn.Module:
    """
    根据 config 构建 TSE 模型并加载预训练权重。

    支持:
      - BSRNN          (bsrnn_legacy.py 中的旧版 BSRNN，通过 wesep 的 legacy 路径)
      - TSE_BSRNN_SPK  (wesep_real_tse 新版联合模型)
      - TFGridNet      (如有)
    """
    from wesep.models import get_model

    model_name = cfg["model"]["tse_model"]
    model_args = dict(cfg["model_args"]["tse_model"])  # 浅拷贝，避免修改原 cfg

    # 将 spk_model_init 中的相对路径解析为绝对路径
    if "spk_model_init" in model_args and model_args["spk_model_init"]:
        smi = model_args["spk_model_init"]
        if not os.path.isabs(smi):
            smi_abs = str((Path(_SCRIPT_DIR) / smi).resolve())
            model_args["spk_model_init"] = smi_abs
            logging.info(f"[TSE] spk_model_init 解析为: {smi_abs}")

    model_cls = get_model(model_name)
    model = model_cls(**model_args)  # 展开 dict 为关键字参数

    if pretrained_path is not None and pretrained_path != "null":
        pretrained_path = str(Path(_SCRIPT_DIR) / pretrained_path)
        logging.info(f"[TSE] 从预训练权重加载: {pretrained_path}")
        ckpt = torch.load(pretrained_path, map_location="cpu")
        # 兼容多种 checkpoint 格式
        # wesep 训练保存格式：{"models": [state_dict], "optimizers": [...], ...}
        if isinstance(ckpt, dict) and "models" in ckpt:
            models_val = ckpt["models"]
            if isinstance(models_val, list) and len(models_val) > 0:
                state_dict = models_val[0]
            elif isinstance(models_val, dict):
                state_dict = models_val
            else:
                state_dict = ckpt
        else:
            state_dict = ckpt.get("model", ckpt.get("state_dict", ckpt)) if isinstance(ckpt, dict) else ckpt
        missing, unexpected = model.load_state_dict(state_dict, strict=False)
        if missing:
            logging.warning(f"[TSE] missing keys ({len(missing)}): {missing[:5]}...")
        if unexpected:
            logging.warning(f"[TSE] unexpected keys ({len(unexpected)}): {unexpected[:5]}...")

    return model


# ===========================================================================
# ASR 模型 (Whisper，冻结)
# ===========================================================================

class FrozenWhisperASR(nn.Module):
    """
    封装冻结的 Whisper ASR 模型（使用 HuggingFace transformers）。
    用于从 TSE 输出音频中提取文字级别的 cross-entropy loss。

    前向输入: 已提取的音频波形 (float32, 16kHz)
    前向输出: CE loss scalar（可反向传播到 TSE 模型）

    梯度路径: tse_wav -> STFT -> mel filterbank -> log_mel -> encoder -> decoder -> CE loss
    """

    # Whisper 固定参数
    N_FFT     = 400
    HOP       = 160
    N_MELS    = 128   # large-v3 使用 128 mel bins
    MAX_FRAME = 3000  # 30s at 10ms shift，16kHz
    SAMPLE_RATE = 16000

    def __init__(self, model_path: str, device: str = "cuda"):
        super().__init__()
        from transformers import WhisperForConditionalGeneration, WhisperTokenizer, WhisperConfig

        logging.info(f"[ASR] 加载 Whisper 模型 (transformers): {model_path}")
        self.hf_model = WhisperForConditionalGeneration.from_pretrained(
            model_path,
            dtype=torch.float32,
        )

        # 冻结所有参数
        for p in self.hf_model.parameters():
            p.requires_grad_(False)
        self.hf_model.eval()

        # 加载 tokenizer
        self.tokenizer = WhisperTokenizer.from_pretrained(model_path)

        # 预计算 mel 滤波器（固定矩阵，不需要梯度）
        # 使用 torchaudio 的 mel_scale_fbanks
        mel_fb = torchaudio.functional.melscale_fbanks(
            n_freqs=self.N_FFT // 2 + 1,
            f_min=0.0,
            f_max=8000.0,
            n_mels=self.N_MELS,
            sample_rate=self.SAMPLE_RATE,
            norm="slaney",
            mel_scale="slaney",
        )  # [n_freqs, n_mels]
        self.register_buffer("mel_fb", mel_fb)  # 不参与梯度，跟随 .to(device) 移动

        logging.info(f"[ASR] Whisper 参数已冻结，mel_bins={self.N_MELS}")

    def _compute_mel_with_grad(self, wav: torch.Tensor) -> torch.Tensor:
        """
        计算可微分的 log-mel spectrogram（全部 PyTorch 操作，梯度可回传）。
        与 WhisperFeatureExtractor 的结果保持一致。

        输入: wav [T]，float32，16kHz
        输出: log_mel [1, N_MELS, MAX_FRAME]
        """
        device = wav.device
        window = torch.hann_window(self.N_FFT, device=device)

        stft = torch.stft(
            wav,
            n_fft=self.N_FFT,
            hop_length=self.HOP,
            window=window,
            return_complex=True,
        )  # [F, T_stft]，F = N_FFT/2+1

        magnitudes = stft.abs() ** 2  # power spectrum [F, T_stft]

        # mel_fb: [F, N_MELS]，magnitudes: [F, T_stft]
        mel_spec = self.mel_fb.T @ magnitudes   # [N_MELS, T_stft]

        # log 压缩（与 WhisperFeatureExtractor 一致：log10 + 归一化）
        log_mel = (mel_spec.clamp(min=1e-10)).log10()
        log_mel = torch.maximum(log_mel, log_mel.max() - 8.0)
        log_mel = (log_mel + 4.0) / 4.0

        # Pad / trim 到 MAX_FRAME
        T = log_mel.shape[-1]
        if T < self.MAX_FRAME:
            log_mel = F.pad(log_mel, (0, self.MAX_FRAME - T))
        else:
            log_mel = log_mel[:, :self.MAX_FRAME]

        return log_mel.unsqueeze(0)  # [1, N_MELS, MAX_FRAME]

    def forward(
        self,
        audio: torch.Tensor,                    # [B, T]，float32，16kHz
        transcripts: List[str],
        language: Optional[str] = None,         # 全局默认语言（None=逐样本使用 languages）
        languages: Optional[List[str]] = None,  # 每条样本的语言列表（优先级高于 language）
    ) -> torch.Tensor:
        """
        Teacher-forcing CE loss。

        参数:
            audio:       TSE 输出的单通道音频 [B, T]
            transcripts: 目标文本列表，长度 B
            language:    全局解码语言，'zh' / 'en'（当 languages 为 None 时使用）
            languages:   每条样本的语言列表（优先使用，修复混合语言 batch 的问题）

        返回:
            loss: scalar Tensor（CE loss，可反向传播到 TSE 模型）
        """
        if audio.dim() == 1:
            audio = audio.unsqueeze(0)
        B = audio.shape[0]

        # 确定每条样本的语言
        if languages is not None and len(languages) == B:
            per_sample_lang = languages
        elif language is not None:
            per_sample_lang = [language] * B
        else:
            per_sample_lang = ["zh"] * B  # 兜底默认

        sot_id = self.tokenizer.convert_tokens_to_ids("<|startoftranscript|>")
        eot_id = self.tokenizer.eos_token_id
        task_token  = "<|transcribe|>"
        notimestamp = "<|notimestamps|>"

        total_loss  = torch.tensor(0.0, device=audio.device, requires_grad=True)
        valid_count = 0

        for i in range(B):
            wav = audio[i]  # [T]

            # ── 逐样本确定语言 token ──────────────────────────────────────
            lang_i = per_sample_lang[i]
            lang_token = f"<|{lang_i}|>"
            forced_prefix_ids = self.tokenizer.convert_tokens_to_ids(
                [lang_token, task_token, notimestamp]
            )

            # ── 可微分 mel 计算（梯度通路）────────────────────────────────
            mel_with_grad = self._compute_mel_with_grad(wav)  # [1, N_MELS, MAX_FRAME]

            # ── Encoder forward（保留梯度通路）───────────────────────────
            enc_out = self.hf_model.model.encoder(
                input_features=mel_with_grad
            ).last_hidden_state  # [1, T_enc, D]

            # ── Tokenize 目标文本 ─────────────────────────────────────────
            text_ids = self.tokenizer.encode(
                transcripts[i], add_special_tokens=False
            )
            # decoder 输入: [SOT, lang, task, notimestamp, text..., EOT]
            full_ids     = [sot_id] + forced_prefix_ids + text_ids + [eot_id]
            decoder_in   = torch.tensor(full_ids[:-1], dtype=torch.long,
                                        device=audio.device).unsqueeze(0)  # [1, L-1]
            decoder_tgt  = torch.tensor(full_ids[1:],  dtype=torch.long,
                                        device=audio.device).unsqueeze(0)  # [1, L-1]

            # ── Decoder forward（teacher-forcing）────────────────────────
            dec_out = self.hf_model.model.decoder(
                input_ids=decoder_in,
                encoder_hidden_states=enc_out,
            ).last_hidden_state  # [1, L-1, D]

            # ── 投影到词表 ────────────────────────────────────────────────
            logits = self.hf_model.proj_out(dec_out)  # [1, L-1, V]

            logits_flat = logits.view(-1, logits.shape[-1])  # [(L-1), V]
            target_flat = decoder_tgt.view(-1)               # [(L-1)]

            loss_i = F.cross_entropy(logits_flat, target_flat, ignore_index=-100)
            total_loss  = total_loss + loss_i
            valid_count += 1

        if valid_count == 0:
            return total_loss

        return total_loss / valid_count

    def decode(
        self,
        audio: torch.Tensor,
        language: str = "zh",
    ) -> List[str]:
        """
        推理解码（不计算梯度），用于日志记录。
        """
        from transformers import WhisperProcessor

        if audio.dim() == 1:
            audio = audio.unsqueeze(0)

        results = []
        with torch.no_grad():
            for i in range(audio.shape[0]):
                wav_np = audio[i].float().cpu().numpy()
                # 使用 generate 接口（HuggingFace 标准推理）
                processor = WhisperProcessor.from_pretrained(
                    self.tokenizer.name_or_path
                    if hasattr(self.tokenizer, "name_or_path") else "openai/whisper-large-v3"
                )
                inputs = processor(
                    wav_np,
                    sampling_rate=self.SAMPLE_RATE,
                    return_tensors="pt",
                ).input_features.to(next(self.hf_model.parameters()).device)
                pred_ids = self.hf_model.generate(
                    inputs,
                    language=language,
                    task="transcribe",
                )
                text = self.tokenizer.decode(pred_ids[0], skip_special_tokens=True)
                results.append(text)
        return results


# ===========================================================================
# 说话人编码器（冻结，用于相似度 Loss）
# 使用与评估侧（wespeakerruntime）完全一致的 ResNet34 编码器：
#   - 英文数据集（CHiME6/AMI）：voxceleb_resnet34_LM
#   - 中文数据集（AliMeeting/AISHELL-4）：cnceleb_resnet34_LM
# 特征提取与 wespeakerruntime/speaker.py 的 _compute_fbank 完全对齐：
#   waveform * 32768 → kaldi.fbank(80mel, 25ms/10ms, hamming) → CMN(axis=0)
# ===========================================================================

class FrozenSpeakerEncoder(nn.Module):
    """
    加载预训练 wespeaker ResNet34 说话人编码器并冻结所有参数。
    特征提取与评估侧 wespeakerruntime 完全对齐，消除 train-eval mismatch。

    forward 输入: 音频波形 [B, T]，float32，16kHz
    forward 输出: speaker embedding [B, D]

    特征提取流程（与 wespeakerruntime/speaker.py._compute_fbank 一致）：
      wav * 32768 → kaldi.fbank(n_mels=80, frame_length=25ms, frame_shift=10ms,
                                window_type='hamming', dither=0.0)
      → CMN（按频率维度减均值，axis=0 即 dim=1）
    """

    def __init__(self, model_dir: str, device: str = "cuda"):
        super().__init__()
        import yaml as _yaml
        import torchaudio.compliance.kaldi as kaldi  # noqa: F401（确认可用）

        model_dir = Path(model_dir)
        config_path = model_dir / "config.yaml"
        model_path  = model_dir / "avg_model.pt"

        if not config_path.exists():
            raise FileNotFoundError(f"[SpeakerEncoder] config.yaml 不存在: {config_path}")
        if not model_path.exists():
            raise FileNotFoundError(f"[SpeakerEncoder] avg_model.pt 不存在: {model_path}")

        with open(config_path, "r", encoding="utf-8") as f:
            spk_cfg = _yaml.safe_load(f)

        # wespeaker ResNet34 的 config 结构：model / model_args
        spk_model_name   = spk_cfg.get("model", "ResNet34")
        spk_model_kwargs = spk_cfg.get("model_args", {})

        from wespeaker.models.speaker_model import get_speaker_model
        spk_cls = get_speaker_model(spk_model_name)
        self.encoder = spk_cls(**spk_model_kwargs)

        ckpt = torch.load(str(model_path), map_location="cpu")
        # 兼容多种 checkpoint 格式
        if isinstance(ckpt, dict) and "model" in ckpt:
            state_dict = ckpt["model"]
        elif isinstance(ckpt, dict) and "state_dict" in ckpt:
            state_dict = ckpt["state_dict"]
        else:
            state_dict = ckpt

        missing, unexpected = self.encoder.load_state_dict(state_dict, strict=False)
        if missing:
            logging.warning(f"[SpeakerEncoder] missing keys ({len(missing)}): {missing[:3]}")
        if unexpected:
            logging.warning(f"[SpeakerEncoder] unexpected keys ({len(unexpected)}): {unexpected[:3]}")

        # 冻结所有参数
        for p in self.encoder.parameters():
            p.requires_grad_(False)
        self.encoder.eval()

        # fbank 参数（与 wespeakerruntime 一致）
        self.sample_rate   = 16000
        self.num_mel_bins  = spk_model_kwargs.get("feat_dim", 80)
        self.frame_length  = 25    # ms
        self.frame_shift   = 10    # ms

        logging.info(
            f"[SpeakerEncoder] 已加载并冻结 ResNet34: {model_path}  "
            f"fbank: n_mels={self.num_mel_bins}, frame_length={self.frame_length}ms, "
            f"frame_shift={self.frame_shift}ms"
        )

    def _wav_to_fbank(self, wav: torch.Tensor) -> torch.Tensor:
        """
        将原始波形 [B, T] 转换为 fbank 特征 [B, T_frames, feat_dim]。
        与 wespeakerruntime/speaker.py._compute_fbank 完全对齐：
          1. wav * 32768（幅度缩放）
          2. kaldi.fbank（hamming 窗，dither=0）
          3. CMN：按频率维度（dim=2）减均值

        注意：kaldi.fbank 不支持 batch，需逐样本处理后 stack。
        该方法支持梯度传播（kaldi.fbank 内部为可微操作）。
        """
        import torchaudio.compliance.kaldi as kaldi

        B = wav.shape[0]
        fbank_list = []
        for i in range(B):
            w = wav[i].unsqueeze(0)          # [1, T]
            w = w * (1 << 15)                # 幅度缩放 ×32768
            feat = kaldi.fbank(
                w,
                num_mel_bins=self.num_mel_bins,
                frame_length=self.frame_length,
                frame_shift=self.frame_shift,
                dither=0.0,
                sample_frequency=self.sample_rate,
                window_type="hamming",
                use_energy=False,
            )  # [T_frames, feat_dim]
            # CMN：按频率维度减均值（axis=0 in numpy = dim=0 in 2D tensor）
            feat = feat - feat.mean(dim=0, keepdim=True)  # [T_frames, feat_dim]
            fbank_list.append(feat)

        # pad 到相同长度后 stack
        max_len = max(f.shape[0] for f in fbank_list)
        padded = []
        for f in fbank_list:
            if f.shape[0] < max_len:
                pad = torch.zeros(max_len - f.shape[0], f.shape[1],
                                  dtype=f.dtype, device=f.device)
                f = torch.cat([f, pad], dim=0)
            padded.append(f)
        return torch.stack(padded, dim=0)  # [B, T_frames, feat_dim]

    def forward(self, wav: torch.Tensor) -> torch.Tensor:
        """
        输入: [B, T] 或 [T]，float32，16kHz 原始波形
        输出: [B, D] speaker embedding
        """
        if wav.dim() == 1:
            wav = wav.unsqueeze(0)
        fbank = self._wav_to_fbank(wav)          # [B, T_frames, feat_dim]
        with torch.no_grad():
            emb = self.encoder(fbank)
        # ResNet34 返回 (frame_feats, embedding) 或直接 embedding
        if isinstance(emb, (tuple, list)):
            emb = emb[-1]
        return emb  # [B, D]


# ===========================================================================
# 说话人相似度 Ranking Loss（可选）
# 支持双编码器：英文用 en_encoder，中文用 chs_encoder
# 按每条样本的语言（languages 列表）选择对应编码器
# ===========================================================================

class SpeakerSimilarityLoss(nn.Module):
    """
    Hinge ranking loss：
      要求 TSE 输出与注册音频的余弦相似度 > mix 音频与注册音频的相似度 + margin
      loss = mean( max(0, margin - (sim(tse, enroll) - sim(mix, enroll))) )

    支持双编码器（en/chs），按 languages 列表逐样本选择编码器。
    梯度仅流经 tse_wav（enroll 和 mix 的编码在 no_grad 下计算）。
    """

    # 数据集语言映射（与评估侧 dataset_lang_overrides 保持一致）
    DATASET_TO_LANG = {
        "CHiME6":    "en",
        "AMI":       "en",
        "DipCo":     "en",
        "AliMeeting": "zh",
        "AISHELL-4": "zh",
    }

    def __init__(
        self,
        en_encoder:  FrozenSpeakerEncoder,
        chs_encoder: FrozenSpeakerEncoder,
        margin: float = 0.2,
    ):
        super().__init__()
        self.en_encoder  = en_encoder
        self.chs_encoder = chs_encoder
        self.margin      = margin

    def _get_encoder(self, lang: str) -> FrozenSpeakerEncoder:
        """根据语言返回对应编码器（zh/chs → chs_encoder，其余 → en_encoder）"""
        if lang in ("zh", "chs", "cn"):
            return self.chs_encoder
        return self.en_encoder

    def forward(
        self,
        tse_wav:    torch.Tensor,    # [B, T_tse]
        mix_wav:    torch.Tensor,    # [B, T_mix]
        enroll_wav: torch.Tensor,    # [B, T_e]
        languages:  List[str],       # 每条样本的语言，长度 B
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        返回: (loss, sim_tse_enroll_mean, sim_mix_enroll_mean)
          - loss: 标量，可反向传播
          - sim_tse_enroll_mean / sim_mix_enroll_mean: 用于日志记录的标量（detach）
        """
        B = tse_wav.shape[0]
        emb_tse_list    = []
        emb_enroll_list = []
        emb_mix_list    = []

        for i in range(B):
            enc = self._get_encoder(languages[i])

            # enroll & mix embedding：冻结，无梯度
            with torch.no_grad():
                e_enroll = enc(enroll_wav[i:i+1])   # [1, D]
                e_mix    = enc(mix_wav[i:i+1])       # [1, D]
                e_enroll = F.normalize(e_enroll, dim=-1)
                e_mix    = F.normalize(e_mix,    dim=-1)

            # tse embedding：需要梯度（通过 tse_wav -> fbank -> encoder 反向传播）
            # 编码器参数冻结，但音频信号梯度可流过 _wav_to_fbank 和 encoder
            fbank_tse = enc._wav_to_fbank(tse_wav[i:i+1])   # [1, T_frames, feat_dim]
            e_tse = enc.encoder(fbank_tse)
            if isinstance(e_tse, (tuple, list)):
                e_tse = e_tse[-1]
            e_tse = F.normalize(e_tse, dim=-1)               # [1, D]

            emb_tse_list.append(e_tse)
            emb_enroll_list.append(e_enroll)
            emb_mix_list.append(e_mix)

        emb_tse    = torch.cat(emb_tse_list,    dim=0)  # [B, D]
        emb_enroll = torch.cat(emb_enroll_list, dim=0)  # [B, D]
        emb_mix    = torch.cat(emb_mix_list,    dim=0)  # [B, D]

        sim_tse_enroll = (emb_tse * emb_enroll).sum(dim=-1)  # [B]
        sim_mix_enroll = (emb_mix * emb_enroll).sum(dim=-1)  # [B]

        loss = F.relu(self.margin - (sim_tse_enroll - sim_mix_enroll)).mean()

        return loss, sim_tse_enroll.detach().mean(), sim_mix_enroll.detach().mean()


# ===========================================================================
# 目标说话人活动检测 Loss（Target VAD Loss）
# ===========================================================================

class TargetVADLoss(nn.Module):
    """
    目标说话人活动检测 (Target Voice Activity Detection) 损失。

    思想：TSE 模型输出的音频在目标说话人不说话的帧上应当接近静音（能量很低），
    而在目标说话人说话的帧上应当有较高能量。

    具体实现：
      1. 将 TSE 输出音频按帧分段，计算每帧的能量（RMS 或 log power）
      2. 根据 target_activity_segments 标签生成逐帧的 0/1 二值标签
      3. 使用 Binary Cross-Entropy 损失对帧级能量进行监督

    帧移 (frame_shift) 和帧长 (frame_length) 可配置，默认 10ms shift, 25ms window @ 16kHz

    梯度路径：tse_wav -> 帧能量 -> sigmoid -> BCE loss
    """

    def __init__(
        self,
        sample_rate: int = 16000,
        frame_shift_ms: float = 10.0,
        frame_length_ms: float = 25.0,
        energy_floor: float = 1e-8,
    ):
        super().__init__()
        self.sample_rate = sample_rate
        self.frame_shift = int(sample_rate * frame_shift_ms / 1000.0)
        self.frame_length = int(sample_rate * frame_length_ms / 1000.0)
        self.energy_floor = energy_floor

    def _compute_frame_energy(self, wav: torch.Tensor) -> torch.Tensor:
        """
        计算逐帧 log 能量（可微分）。

        输入: wav [B, T]
        输出: energy [B, N_frames]，经过 sigmoid 归一化到 [0, 1]
        """
        B, T = wav.shape
        # 使用 unfold 分帧（可微分操作）
        # wav: [B, T] -> frames: [B, N_frames, frame_length]
        frames = wav.unfold(dimension=1, size=self.frame_length, step=self.frame_shift)
        # 计算每帧的均方根能量
        rms = (frames ** 2).mean(dim=-1).clamp(min=self.energy_floor)  # [B, N_frames]
        # log 能量 -> sigmoid 归一化到 (0, 1) 作为 "活动概率"
        log_energy = torch.log(rms)
        # 使用可学习的归一化：将 log_energy 映射到合理范围后做 sigmoid
        # 典型范围：静音约 -18 (1e-8 的 log)，正常语音约 -2 ~ -5
        # 线性缩放后 sigmoid：(log_energy + 10) / 5 使得 -15 -> -1 (sig=0.27), -5 -> 1 (sig=0.73)
        activity_prob = torch.sigmoid((log_energy + 10.0) / 5.0)  # [B, N_frames]
        return activity_prob

    def _segments_to_frame_labels(
        self,
        segments: List[List[float]],
        num_frames: int,
        device: torch.device,
    ) -> torch.Tensor:
        """
        将时间段标签 [[start1, end1], [start2, end2], ...] 转换为逐帧 0/1 标签。

        segments 中的时间单位为秒（相对于 mixture 起始的偏移）。
        输出: [num_frames] float Tensor, 1.0=说话, 0.0=静音
        """
        labels = torch.zeros(num_frames, device=device)
        for seg in segments:
            start_sec, end_sec = seg[0], seg[1]
            start_frame = int(start_sec * self.sample_rate / self.frame_shift)
            end_frame   = int(end_sec   * self.sample_rate / self.frame_shift)
            start_frame = max(0, min(start_frame, num_frames))
            end_frame   = max(0, min(end_frame,   num_frames))
            if start_frame < end_frame:
                labels[start_frame:end_frame] = 1.0
        return labels

    def forward(
        self,
        tse_wav: torch.Tensor,                        # [B, T]
        vad_segments: List[Optional[List[List[float]]]],  # batch 中每条样本的 VAD segments
        mix_lens: torch.Tensor,                       # [B] 实际长度
    ) -> torch.Tensor:
        """
        计算目标说话人活动检测 BCE 损失。

        参数:
            tse_wav:      TSE 输出音频 [B, T]
            vad_segments: 每条样本的 VAD 时间段列表（None 表示该样本无标签，跳过）
            mix_lens:     每条样本的实际音频长度（采样点数）

        返回:
            loss: 标量 Tensor（可反向传播）
        """
        B = tse_wav.shape[0]
        device = tse_wav.device

        # 计算帧级活动概率
        activity_prob = self._compute_frame_energy(tse_wav)  # [B, N_frames]
        N_frames = activity_prob.shape[1]

        total_loss = torch.tensor(0.0, device=device, requires_grad=True)
        valid_count = 0

        for i in range(B):
            if vad_segments[i] is None:
                continue

            # 该样本实际帧数
            actual_len = mix_lens[i].item()
            actual_frames = min(
                int(actual_len / self.frame_shift),
                N_frames,
            )
            if actual_frames <= 0:
                continue

            # 生成帧级标签
            labels = self._segments_to_frame_labels(
                vad_segments[i], actual_frames, device
            )  # [actual_frames]

            # 截取对应帧的预测
            pred = activity_prob[i, :actual_frames]  # [actual_frames]

            # BCE loss
            loss_i = F.binary_cross_entropy(pred, labels, reduction="mean")
            total_loss = total_loss + loss_i
            valid_count += 1

        if valid_count == 0:
            return total_loss

        return total_loss / valid_count


# ===========================================================================
# 学习率调度器
# ===========================================================================

class ExponentialDecayScheduler:
    """
    指数衰减学习率调度器（与 wesep 中保持一致）。

    warm_up_epoch 轮内从 initial_lr 线性预热（或从 0 开始），
    之后按指数从 initial_lr 衰减到 final_lr。
    """

    def __init__(
        self,
        optimizer: torch.optim.Optimizer,
        initial_lr: float,
        final_lr: float,
        num_epochs: int,
        epoch_iter: int,
        warm_up_epoch: int = 1,
        warm_from_zero: bool = False,
    ):
        self.optimizer      = optimizer
        self.initial_lr     = initial_lr
        self.final_lr       = final_lr
        self.num_epochs     = num_epochs
        self.epoch_iter     = epoch_iter
        self.warm_up_epoch  = warm_up_epoch
        self.warm_from_zero = warm_from_zero
        self.total_steps    = num_epochs * epoch_iter
        self.warm_steps     = warm_up_epoch * epoch_iter
        self._step          = 0

    def step(self):
        self._step += 1
        lr = self._get_lr()
        for pg in self.optimizer.param_groups:
            pg["lr"] = lr

    def _get_lr(self) -> float:
        if self._step <= self.warm_steps and self.warm_steps > 0:
            start = 0.0 if self.warm_from_zero else self.initial_lr
            frac  = self._step / self.warm_steps
            return start + frac * (self.initial_lr - start)

        # 指数衰减阶段
        decay_steps = self.total_steps - self.warm_steps
        step_in_decay = self._step - self.warm_steps
        if decay_steps <= 0:
            return self.final_lr
        frac = step_in_decay / decay_steps
        # log-linear 插值
        lr = self.initial_lr * (self.final_lr / self.initial_lr) ** frac
        return float(np.clip(lr, self.final_lr, self.initial_lr))

    def get_last_lr(self) -> float:
        return self._get_lr()

    def state_dict(self) -> Dict:
        return {"_step": self._step}

    def load_state_dict(self, d: Dict):
        self._step = d["_step"]


# ===========================================================================
# Checkpoint 工具
# ===========================================================================

def save_checkpoint(
    path: str,
    step: int,
    epoch: int,
    tse_model: nn.Module,
    optimizer: torch.optim.Optimizer,
    scheduler: ExponentialDecayScheduler,
    best_loss: float,
):
    torch.save(
        {
            "step":      step,
            "epoch":     epoch,
            "model":     tse_model.state_dict(),
            "optimizer": optimizer.state_dict(),
            "scheduler": scheduler.state_dict(),
            "best_loss": best_loss,
        },
        path,
    )


def load_checkpoint(
    path: str,
    tse_model: nn.Module,
    optimizer: Optional[torch.optim.Optimizer] = None,
    scheduler: Optional[ExponentialDecayScheduler] = None,
) -> Tuple[int, int, float]:
    """
    返回 (step, epoch, best_loss)
    """
    logging.info(f"[Ckpt] 从 {path} 恢复训练")
    ckpt = torch.load(path, map_location="cpu")
    tse_model.load_state_dict(ckpt["model"])
    if optimizer is not None and "optimizer" in ckpt:
        optimizer.load_state_dict(ckpt["optimizer"])
    if scheduler is not None and "scheduler" in ckpt:
        scheduler.load_state_dict(ckpt["scheduler"])
    return ckpt.get("step", 0), ckpt.get("epoch", 0), ckpt.get("best_loss", float("inf"))


def rotate_checkpoints(ckpt_dir: str, max_keep: int):
    """保留最新 max_keep 个 checkpoint_step*.pt，删除旧的"""
    ckpts = sorted(Path(ckpt_dir).glob("checkpoint_step*.pt"))
    if len(ckpts) > max_keep:
        for old in ckpts[: len(ckpts) - max_keep]:
            old.unlink()
            logging.debug(f"[Ckpt] 删除旧 checkpoint: {old.name}")


# ===========================================================================
# 训练主循环
# ===========================================================================

def run_tse_forward(
    tse_model: nn.Module,
    mixture: torch.Tensor,     # [B, T]
    enroll: torch.Tensor,      # [B, T_e]
) -> torch.Tensor:
    """
    调用 TSE 模型提取目标说话人音频。
    兼容 wesep BSRNN（旧版）和 TSE_BSRNN_SPK（新版）两种接口。

    返回: tse_out [B, T]（与 mixture 长度相同）
    """
    out = tse_model(mixture, enroll)

    # 处理不同返回格式
    if isinstance(out, (tuple, list)):
        tse_out = out[0]  # 第一个输出为分离音频
    else:
        tse_out = out

    # 确保 shape 为 [B, T]
    if tse_out.dim() == 3:
        tse_out = tse_out.squeeze(1)   # [B, 1, T] -> [B, T]

    return tse_out


def train_one_epoch(
    tse_model:    nn.Module,
    asr_model:    Optional[FrozenWhisperASR],
    dataloader:   DataLoader,
    optimizer:    torch.optim.Optimizer,
    scheduler:    ExponentialDecayScheduler,
    device:       torch.device,
    epoch:        int,
    global_step:  int,
    cfg:          Dict,
    writer:       Optional[SummaryWriter],
    logger:       logging.Logger,
    spk_loss_fn:   Optional[SpeakerSimilarityLoss] = None,
    vad_loss_fn:   Optional[TargetVADLoss] = None,
    dnsmos_loss_fn = None,
    is_main:       bool = True,
    world_size:   int = 1,
) -> Tuple[float, int]:
    """
    单 epoch 训练。返回 (epoch_loss, global_step)
    多卡：每张卡独立跑 dataloader 的一个分片，loss 通过 all-reduce 同步后 rank0 写日志。
    Checkpoint 仅 rank0（is_main=True）写入。
    """
    tse_model.train()

    loss_mode      = cfg.get("loss_mode", "combined")
    lambda_ce      = cfg.get("lambda_ce",      1.0)
    lambda_sim     = cfg.get("lambda_sim",     0.5)
    lambda_vad     = cfg.get("lambda_vad",     0.5)
    lambda_dnsmos  = cfg.get("lambda_dnsmos",  0.0)
    # 兼容旧版 lambda_spk
    if cfg.get("lambda_spk", 0.0) > 0 and loss_mode == "ce":
        loss_mode  = "combined"
        lambda_sim = cfg["lambda_spk"]

    clip_grad      = cfg.get("clip_grad", 5.0)
    log_every      = cfg.get("log_every", 20)
    save_step_int  = cfg.get("save_step_interval", 500)
    max_keep_ckpts = cfg.get("max_keep_ckpts", 3)
    exp_dir        = cfg["exp_dir"]
    model_dir      = Path(exp_dir) / "models"
    asr_language   = cfg.get("asr_language", "zh")

    # 三种 loss 模式校验
    valid_modes = ("ce", "similarity", "combined")
    if loss_mode not in valid_modes:
        raise ValueError(f"[Train] 无效 loss_mode={loss_mode!r}，合法值: {valid_modes}")
    if loss_mode in ("similarity", "combined") and spk_loss_fn is None:
        raise ValueError(
            f"[Train] loss_mode={loss_mode!r} 需要 spk_loss_fn，"
            "请在 config 中配置 spk_encoder_path"
        )
    if loss_mode in ("ce", "combined") and asr_model is None:
        raise ValueError(
            f"[Train] loss_mode={loss_mode!r} 需要 asr_model，"
            "请在 config 中配置 whisper_model_path"
        )

    enable_amp    = cfg.get("enable_amp", False)
    amp_dtype_str = cfg.get("amp_dtype", "float32")
    amp_dtype     = torch.bfloat16 if amp_dtype_str == "bfloat16" else torch.float16
    scaler        = torch.cuda.amp.GradScaler(enabled=enable_amp and amp_dtype != torch.bfloat16)

    # 取 raw module（用于 checkpoint 保存和获取 spk_encoder）
    raw_model = tse_model.module if hasattr(tse_model, "module") else tse_model

    running_loss   = 0.0
    running_ce     = 0.0
    running_sim    = 0.0
    running_vad    = 0.0
    running_dnsmos = 0.0
    n_batches      = 0
    best_loss    = cfg.get("_best_loss", float("inf"))

    # 仅 rank0 显示进度条
    pbar = tqdm(dataloader, desc=f"Epoch {epoch}", dynamic_ncols=True, leave=False,
                disable=not is_main)

    for batch in pbar:
        if batch is None:
            continue

        mixture      = batch["mixture"].to(device)       # [B, T]
        enroll       = batch["enroll"].to(device)        # [B, T_e]
        mix_lens     = batch["mix_lens"].to(device)      # [B]
        transcripts  = batch["transcripts"]              # List[str]
        languages    = batch.get("languages", None)      # List[str] 或 None
        vad_segments = batch.get("vad_segments", None)   # List[Optional[List]]

        optimizer.zero_grad()

        # ── 1. TSE 前向 ─────────────────────────────────────────────────
        with torch.cuda.amp.autocast(enabled=enable_amp, dtype=amp_dtype):
            tse_out = run_tse_forward(tse_model, mixture, enroll)  # [B, T]

        # ── 2. ASR CE Loss ──────────────────────────────────────────────
        ce_loss     = torch.tensor(0.0, device=device)
        sim_loss    = torch.tensor(0.0, device=device)
        vad_loss    = torch.tensor(0.0, device=device)
        dnsmos_loss = torch.tensor(0.0, device=device)
        sim_tse_enroll_mean = torch.tensor(0.0, device=device)
        sim_mix_enroll_mean = torch.tensor(0.0, device=device)

        if loss_mode in ("ce", "combined"):
            # 使用 batch 中每条样本的实际语言（修复中英混合 batch 的语言偏置问题）
            ce_loss = asr_model(
                tse_out,
                transcripts,
                language=asr_language,   # 兜底语言（当 languages 为 None 时使用）
                languages=languages,     # 优先使用逐样本语言
            )

        # ── 3. 说话人相似度 Ranking Loss ────────────────────────────────
        # 目标：sim(tse_out, enroll) > sim(mix, enroll) + margin
        # 按每条样本的语言选择对应编码器（en/chs）
        if loss_mode in ("similarity", "combined") and spk_loss_fn is not None:
            try:
                sim_loss, sim_tse_enroll_mean, sim_mix_enroll_mean = spk_loss_fn(
                    tse_out, mixture, enroll,
                    languages=languages if languages is not None else ["en"] * tse_out.shape[0],
                )
            except Exception as e:
                logger.warning(f"[Train] spk sim loss 计算失败: {e}")
                sim_loss = torch.tensor(0.0, device=device)

        # ── 3.5. 目标说话人活动检测 Loss ─────────────────────────────────
        if loss_mode == "combined" and vad_loss_fn is not None and vad_segments is not None:
            try:
                vad_loss = vad_loss_fn(tse_out, vad_segments, mix_lens)
            except Exception as e:
                logger.warning(f"[Train] VAD loss 计算失败: {e}")
                vad_loss = torch.tensor(0.0, device=device)

        # ── 3.6. 可微分 DNSMOS Loss ─────────────────────────────────────
        # 不需要参考音：DNSMOSLoss.forward 中 ref 仅接口对齐，不参与 DNSMOS 计算
        if loss_mode == "combined" and dnsmos_loss_fn is not None and lambda_dnsmos > 0:
            try:
                dnsmos_loss = dnsmos_loss_fn(inf=tse_out).mean()
            except Exception as e:
                logger.warning(f"[Train] DNSMOS loss 计算失败: {e}")
                dnsmos_loss = torch.tensor(0.0, device=device)

        # ── 4. 合并 Loss ────────────────────────────────────────────────
        if loss_mode == "ce":
            loss = lambda_ce * ce_loss
        elif loss_mode == "similarity":
            loss = lambda_sim * sim_loss
        else:  # combined
            loss = (lambda_ce    * ce_loss
                  + lambda_sim   * sim_loss
                  + lambda_vad   * vad_loss
                  + lambda_dnsmos * dnsmos_loss)

        if not torch.isfinite(loss):
            if is_main:
                logger.warning(f"[Train] step={global_step} loss 非有限值，跳过")
            optimizer.zero_grad()
            global_step += 1
            scheduler.step()
            continue

        # ── 5. 反向传播 ─────────────────────────────────────────────────
        if enable_amp and amp_dtype != torch.bfloat16:
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            nn.utils.clip_grad_norm_(tse_model.parameters(), clip_grad)
            scaler.step(optimizer)
            scaler.update()
        else:
            loss.backward()
            nn.utils.clip_grad_norm_(tse_model.parameters(), clip_grad)
            optimizer.step()

        scheduler.step()
        global_step += 1

        # ── 6. 跨卡 loss 同步（用于日志，不影响梯度）────────────────────
        loss_t    = reduce_mean(loss.detach())
        ce_t      = reduce_mean(ce_loss.detach() if torch.is_tensor(ce_loss) else
                                torch.tensor(ce_loss, device=device))
        sim_t     = reduce_mean(sim_loss.detach() if torch.is_tensor(sim_loss) else
                                torch.tensor(sim_loss, device=device))
        vad_t     = reduce_mean(vad_loss.detach() if torch.is_tensor(vad_loss) else
                                torch.tensor(vad_loss, device=device))
        dnsmos_t  = reduce_mean(dnsmos_loss.detach() if torch.is_tensor(dnsmos_loss) else
                                torch.tensor(dnsmos_loss, device=device))
        sim_tse_t = reduce_mean(sim_tse_enroll_mean.detach()
                                if torch.is_tensor(sim_tse_enroll_mean) else
                                torch.tensor(sim_tse_enroll_mean, device=device))
        sim_mix_t = reduce_mean(sim_mix_enroll_mean.detach()
                                if torch.is_tensor(sim_mix_enroll_mean) else
                                torch.tensor(sim_mix_enroll_mean, device=device))

        loss_val    = loss_t.item()
        ce_val      = ce_t.item()
        sim_val     = sim_t.item()
        vad_val       = vad_t.item()
        dnsmos_val    = dnsmos_t.item()
        sim_tse_val   = sim_tse_t.item()
        sim_mix_val   = sim_mix_t.item()
        running_loss   += loss_val
        running_ce     += ce_val
        running_sim    += sim_val
        running_vad    += vad_val
        running_dnsmos += dnsmos_val
        n_batches      += 1

        current_lr = scheduler.get_last_lr()
        if is_main:
            postfix = {"loss": f"{loss_val:.4f}", "lr": f"{current_lr:.2e}"}
            if loss_mode in ("ce", "combined"):
                postfix["ce"] = f"{ce_val:.4f}"
            if loss_mode in ("similarity", "combined"):
                postfix["sim"] = f"{sim_val:.4f}"
            if loss_mode == "combined" and vad_loss_fn is not None:
                postfix["vad"] = f"{vad_val:.4f}"
            if loss_mode == "combined" and dnsmos_loss_fn is not None and lambda_dnsmos > 0:
                postfix["dnsmos_loss"] = f"{dnsmos_val:.4f}"  # 负值，越接近 0 越好
            pbar.set_postfix(postfix)

        if global_step % log_every == 0 and is_main:
            avg_loss   = running_loss   / max(n_batches, 1)
            avg_ce     = running_ce     / max(n_batches, 1)
            avg_sim    = running_sim    / max(n_batches, 1)
            avg_vad    = running_vad    / max(n_batches, 1)
            avg_dnsmos = running_dnsmos / max(n_batches, 1)
            log_parts = (
                f"[Train] epoch={epoch} step={global_step} loss={avg_loss:.4f}"
            )
            if loss_mode in ("ce", "combined"):
                log_parts += f" ce={avg_ce:.4f}"
            if loss_mode in ("similarity", "combined"):
                log_parts += (
                    f" sim={avg_sim:.4f}"
                    f" sim_tse={sim_tse_val:.3f}"
                    f" sim_mix={sim_mix_val:.3f}"
                )
            if loss_mode == "combined" and vad_loss_fn is not None:
                log_parts += f" vad={avg_vad:.4f}"
            if loss_mode == "combined" and dnsmos_loss_fn is not None and lambda_dnsmos > 0:
                log_parts += f" dnsmos_loss={avg_dnsmos:.4f}"
            log_parts += f" lr={current_lr:.2e}"
            logger.info(log_parts)
            if writer is not None:
                writer.add_scalar("train/loss",           avg_loss,       global_step)
                writer.add_scalar("train/ce_loss",        avg_ce,         global_step)
                writer.add_scalar("train/sim_loss",       avg_sim,        global_step)
                writer.add_scalar("train/vad_loss",       avg_vad,        global_step)
                writer.add_scalar("train/dnsmos_loss",    avg_dnsmos,     global_step)
                writer.add_scalar("train/sim_tse_enroll", sim_tse_val,    global_step)
                writer.add_scalar("train/sim_mix_enroll", sim_mix_val,    global_step)
                writer.add_scalar("train/lr",             current_lr,     global_step)
            running_loss = running_ce = running_sim = running_vad = running_dnsmos = 0.0
            n_batches = 0

        # ── 7. 定期保存 checkpoint（仅 rank0）─────────────────────────
        if global_step % save_step_int == 0 and is_main:
            ckpt_path = model_dir / f"checkpoint_step{global_step:07d}.pt"
            save_checkpoint(
                str(ckpt_path),
                step=global_step,
                epoch=epoch,
                tse_model=raw_model,      # 保存 raw module，不含 DDP 包装
                optimizer=optimizer,
                scheduler=scheduler,
                best_loss=best_loss,
            )
            latest = model_dir / "latest_checkpoint.pt"
            if latest.is_symlink() or latest.exists():
                latest.unlink()
            latest.symlink_to(ckpt_path.name)
            rotate_checkpoints(str(model_dir), max_keep_ckpts)
            logger.info(f"[Ckpt] 保存 step={global_step}: {ckpt_path.name}")

    epoch_loss = running_loss / max(n_batches, 1)
    return epoch_loss, global_step


# ===========================================================================
# 配置加载
# ===========================================================================

def load_config(config_path: str, overrides: Optional[Dict] = None) -> Dict:
    with open(config_path, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    if overrides:
        cfg.update(overrides)
    return cfg


def resolve_path(path: str, base: Path) -> str:
    """将相对于脚本目录的路径解析为绝对路径"""
    p = Path(path)
    if not p.is_absolute():
        p = (base / p).resolve()
    return str(p)


def setup_logging(exp_dir: str) -> logging.Logger:
    log_dir = Path(exp_dir)
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / "train.log"

    fmt = "%(asctime)s [%(levelname)s] %(message)s"
    logging.basicConfig(
        level=logging.INFO,
        format=fmt,
        handlers=[
            logging.StreamHandler(sys.stdout),
            logging.FileHandler(str(log_path), mode="a"),
        ],
    )
    return logging.getLogger("tse_asr_train")


# ===========================================================================
# Epoch 后台评估
# ===========================================================================

def launch_async_epoch_eval(
    epoch: int,
    exp_dir: str,
    logger: logging.Logger,
    state: Optional[Dict] = None,
    cfg: Optional[Dict] = None,
) -> Dict:
    """
    在每个 epoch 结束后后台启动一次 REAL-T 全量评估。

    特性：
      - 仅建议在 rank0 调用
      - 默认若上一轮评估仍在运行，则跳过本轮，避免评估堆积
      - 评估完成后，将 output 目录下生成的 *_summary.txt 复制到
        <exp_dir>/eval_summaries/ 中，按 epoch 归档，避免后续覆盖
    """
    state = dict(state or {})
    cfg = cfg or {}

    enabled = cfg.get("epoch_eval_enabled", True)
    if not enabled:
        return state

    prev_proc = state.get("proc")
    skip_if_running = cfg.get("epoch_eval_skip_if_running", True)
    if prev_proc is not None and prev_proc.poll() is None:
        prev_epoch = state.get("epoch")
        prev_log = state.get("log_path")
        if skip_if_running:
            logger.info(
                f"[Eval] 跳过 epoch={epoch}：上一轮后台评估仍在运行 "
                f"(epoch={prev_epoch}, pid={prev_proc.pid}, log={prev_log})"
            )
            return state

    exp_dir_path = Path(exp_dir).resolve()
    real_t_root = (_SCRIPT_DIR.parent / "REAL-TSE-Challenge").resolve()
    output_root = Path(
        cfg.get("epoch_eval_output_root", str(real_t_root / "output"))
    ).resolve()
    test_set = str(cfg.get("epoch_eval_test_set", "DEV")).upper()
    cuda_id = str(cfg.get("epoch_eval_cuda", "2"))
    fast_flag = bool(cfg.get("epoch_eval_fast", True))

    model_label = exp_dir_path.name
    output_dir = output_root / test_set / model_label
    eval_logs_dir = exp_dir_path / "eval_logs"
    eval_summaries_dir = exp_dir_path / "eval_summaries"
    eval_logs_dir.mkdir(parents=True, exist_ok=True)
    eval_summaries_dir.mkdir(parents=True, exist_ok=True)

    log_path = eval_logs_dir / f"eval_epoch{epoch:03d}.log"
    fast_arg = "--fast " if fast_flag else ""

    cmd = f"""set -euo pipefail
cd {shlex.quote(str(real_t_root))}
bash ./run_all_eval.sh {fast_arg}--model {shlex.quote(str(exp_dir_path))} --test-set {shlex.quote(test_set)} --cuda {shlex.quote(cuda_id)}
summary_file=$(find {shlex.quote(str(output_dir))} -maxdepth 1 -type f -name '*_summary.txt' | sort | head -n 1 || true)
if [ -n "$summary_file" ] && [ -f "$summary_file" ]; then
    summary_base=$(basename "$summary_file")
    cp "$summary_file" {shlex.quote(str(eval_summaries_dir))}/epoch_{epoch:03d}_${{summary_base}}
fi
"""

    with open(log_path, "a", encoding="utf-8") as log_f:
        log_f.write(
            f"\n========== epoch {epoch} eval start: {datetime.datetime.now():%Y-%m-%d %H:%M:%S} =========="
            f"\nmodel={exp_dir_path}\ntest_set={test_set}\ncuda={cuda_id}\noutput_dir={output_dir}\n\n"
        )

    proc = subprocess.Popen(
        ["bash", "-lc", cmd],
        stdout=open(log_path, "a", encoding="utf-8"),
        stderr=subprocess.STDOUT,
        start_new_session=True,
    )
    logger.info(
        f"[Eval] 后台启动 epoch={epoch} 评估, pid={proc.pid}, "
        f"output_dir={output_dir}, log={log_path}"
    )
    logger.info(
        f"[Eval] 本轮完成后会归档 summary 到: {eval_summaries_dir}"
    )
    return {
        "proc": proc,
        "epoch": epoch,
        "log_path": str(log_path),
        "output_dir": str(output_dir),
        "summary_dir": str(eval_summaries_dir),
    }


# ===========================================================================
# DDP 工具
# ===========================================================================

def is_dist_avail_and_initialized() -> bool:
    return dist.is_available() and dist.is_initialized()


def get_rank() -> int:
    if not is_dist_avail_and_initialized():
        return 0
    return dist.get_rank()


def get_world_size() -> int:
    if not is_dist_avail_and_initialized():
        return 1
    return dist.get_world_size()


def is_main_process() -> bool:
    return get_rank() == 0


def setup_ddp():
    """
    初始化 DDP。torchrun 会自动设置 RANK / LOCAL_RANK / WORLD_SIZE 环境变量。
    单卡时不做任何事。
    """
    if "LOCAL_RANK" not in os.environ:
        return  # 单卡模式，不初始化

    local_rank = int(os.environ["LOCAL_RANK"])
    torch.cuda.set_device(local_rank)
    dist.init_process_group(backend="nccl")


def cleanup_ddp():
    if is_dist_avail_and_initialized():
        dist.destroy_process_group()


def reduce_mean(tensor: torch.Tensor) -> torch.Tensor:
    """跨卡 all-reduce 取均值（仅多卡时有效）"""
    if not is_dist_avail_and_initialized():
        return tensor
    t = tensor.clone()
    dist.all_reduce(t, op=dist.ReduceOp.SUM)
    t /= get_world_size()
    return t


# ===========================================================================
# 主入口
# ===========================================================================

def main():
    parser = argparse.ArgumentParser(description="TSE-ASR 端到端训练（支持单卡/多卡 DDP）")
    parser.add_argument(
        "--config", "-c",
        type=str, required=True,
        help="训练配置文件路径（YAML）",
    )
    parser.add_argument(
        "--resume",
        type=str, default=None,
        help="从该 checkpoint 文件恢复训练（覆盖 config 中的 resume）",
    )
    parser.add_argument(
        "--exp_dir",
        type=str, default=None,
        help="实验目录（覆盖 config 中的 exp_dir）",
    )
    parser.add_argument(
        "--max_samples",
        type=int, default=None,
        help="最大训练样本数（覆盖 config）",
    )
    args = parser.parse_args()

    # ── DDP 初始化 ────────────────────────────────────────────────────────
    setup_ddp()
    rank       = get_rank()
    world_size = get_world_size()
    local_rank = int(os.environ.get("LOCAL_RANK", 0))
    is_main    = is_main_process()

    # ── 加载配置 ─────────────────────────────────────────────────────────
    cfg = load_config(args.config)

    # 命令行覆盖
    if args.resume      is not None: cfg["resume"]               = args.resume
    if args.exp_dir     is not None: cfg["exp_dir"]              = args.exp_dir
    if args.max_samples is not None: cfg["data"]["max_samples"]  = args.max_samples

    # 生成带时间戳的实验目录（rank0 生成时间戳，广播给所有 rank 保持一致）
    exp_dir_raw = cfg.get("exp_dir", "exp/tse_asr")
    exp_dir_abs = resolve_path(exp_dir_raw, _SCRIPT_DIR)
    # 检查目录名是否已有时间戳前缀（格式：YYYYMMDD_HHMMSS_...）
    _name = Path(exp_dir_abs).name
    _parts = _name.split("_")
    _already_timestamped = (
        len(_parts) >= 2
        and len(_parts[0]) == 8 and _parts[0].isdigit()
        and len(_parts[1]) == 6 and _parts[1].isdigit()
    )
    if not _already_timestamped:
        if is_main:
            ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            # 使用 config 中 exp_dir 的目录名作为模型标签（如 bsrnn_ecapa_vox1）
            model_tag = Path(exp_dir_raw).name
            exp_dir_abs = str(Path(exp_dir_abs).parent / f"{ts}_{model_tag}")
        # 多卡时广播 exp_dir 字符串给所有 rank
        if world_size > 1:
            buf = [exp_dir_abs]
            dist.broadcast_object_list(buf, src=0)
            exp_dir_abs = buf[0]
    cfg["exp_dir"] = exp_dir_abs

    # 仅 rank0 创建目录
    model_dir = Path(exp_dir_abs) / "models"
    tb_dir    = Path(exp_dir_abs) / "tensorboard"
    if is_main:
        model_dir.mkdir(parents=True, exist_ok=True)
        tb_dir.mkdir(parents=True, exist_ok=True)
    if world_size > 1:
        dist.barrier()

    # ── 日志（仅 rank0 写文件，其余 rank 只写 stdout）───────────────────
    logger = setup_logging(exp_dir_abs) if is_main else logging.getLogger("tse_asr_train")
    if not is_main:
        logging.basicConfig(level=logging.WARNING)

    # TensorBoard 仅 rank0
    writer = SummaryWriter(log_dir=str(tb_dir)) if is_main else None

    if is_main:
        logger.info(f"实验目录: {exp_dir_abs}")
        logger.info(f"配置文件: {args.config}")
        logger.info(f"多卡训练: world_size={world_size}")

        config_save_path = Path(exp_dir_abs) / "config.yaml"
        if not config_save_path.exists():
            shutil.copy(args.config, str(config_save_path))

    # ── 随机种子（各 rank 加 rank 偏移）──────────────────────────────────
    seed = cfg.get("seed", 42) + rank
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    # ── 设备 ──────────────────────────────────────────────────────────────
    if torch.cuda.is_available():
        device = torch.device(f"cuda:{local_rank}")
    else:
        device = torch.device("cpu")
    if is_main:
        logger.info(f"rank={rank} 使用设备: {device}，world_size={world_size}")

    # ── 数据集 ────────────────────────────────────────────────────────────
    data_cfg = cfg["data"]

    # 解析训练数据根目录列表，支持三种写法：
    #   train_roots: [path1, path2, ...]   → 多根目录（新写法）
    #   train_root: path                   → 单根目录（旧写法，向后兼容）
    #   两者同时存在时 train_roots 优先
    _roots_raw = data_cfg.get("train_roots", None)
    if _roots_raw is None:
        # 兼容旧字段 train_root（单字符串）
        _root_single = data_cfg.get("train_root", None)
        if _root_single is None:
            raise ValueError("[Data] 配置中必须指定 train_roots 或 train_root")
        _roots_raw = [_root_single]
    elif isinstance(_roots_raw, str):
        _roots_raw = [_roots_raw]

    train_roots = [resolve_path(r, _SCRIPT_DIR) for r in _roots_raw]
    if is_main:
        logger.info(f"[Data] 训练数据根目录: {train_roots}")

    train_dataset = TSEASRDataset(
        train_roots        = train_roots,
        datasets           = data_cfg.get("datasets", ["CHiME6", "AMI", "AliMeeting", "AISHELL-4"]),
        dataset_subdirs    = data_cfg,
        sample_rate        = data_cfg.get("sample_rate", 16000),
        max_mix_len        = data_cfg.get("max_mix_len", 480000),
        max_enroll_len     = data_cfg.get("max_enroll_len", 160000),
        min_transcript_len = data_cfg.get("min_transcript_len", 2),
        max_samples        = data_cfg.get("max_samples", 0),
    )

    # DDP: 用 DistributedSampler 替代 shuffle=True
    sampler = (
        DistributedSampler(train_dataset, num_replicas=world_size, rank=rank, shuffle=True)
        if world_size > 1
        else None
    )
    dataloader = DataLoader(
        train_dataset,
        batch_size  = cfg.get("batch_size", 1),
        shuffle     = (sampler is None),   # 单卡 shuffle，多卡由 sampler 负责
        sampler     = sampler,
        num_workers = cfg.get("num_workers", 4),
        collate_fn  = tse_asr_collate_fn,
        drop_last   = False,
        pin_memory  = True,
    )
    if is_main:
        logger.info(f"DataLoader: {len(train_dataset)} 条样本，{len(dataloader)} 个 batch/epoch/rank")

    # ── TSE 模型 ──────────────────────────────────────────────────────────
    _DEFAULT_TSE = "/home/yuque3/nwy/real-t/REAL-TSE-Challenge/pretrained/bsrnn_ecapa_vox1/avg_model.pt"
    pretrained_tse = cfg.get("pretrained_tse", _DEFAULT_TSE) or _DEFAULT_TSE
    if pretrained_tse and not os.path.isabs(pretrained_tse):
        pretrained_tse = resolve_path(pretrained_tse, _SCRIPT_DIR)

    tse_model = build_tse_model(cfg, pretrained_path=pretrained_tse)
    tse_model = tse_model.to(device)

    # 多卡：封装 DDP
    if world_size > 1:
        tse_model = torch.nn.parallel.DistributedDataParallel(
            tse_model,
            device_ids=[local_rank],
            output_device=local_rank,
            find_unused_parameters=cfg.get("find_unused_parameters", False),
        )

    if is_main:
        _m = tse_model.module if world_size > 1 else tse_model
        n_params = sum(p.numel() for p in _m.parameters())
        n_train  = sum(p.numel() for p in _m.parameters() if p.requires_grad)
        logger.info(f"TSE 模型参数: 总量={n_params/1e6:.2f}M，可训练={n_train/1e6:.2f}M")

    # ── 解析 loss_mode（main 内统一确定）─────────────────────────────────
    loss_mode = cfg.get("loss_mode", "combined")
    # 兼容旧版 lambda_spk
    if cfg.get("lambda_spk", 0.0) > 0 and loss_mode == "ce":
        loss_mode = "combined"
    valid_modes = ("ce", "similarity", "combined")
    if loss_mode not in valid_modes:
        raise ValueError(f"无效 loss_mode={loss_mode!r}，合法值: {valid_modes}")
    if is_main:
        logger.info(f"[Loss] loss_mode={loss_mode}")

    # ── ASR 模型（冻结 Whisper，仅 ce / combined 模式加载）──────────────
    asr_model = None
    if loss_mode in ("ce", "combined"):
        _DEFAULT_WHISPER = "/home/yuque3/nwy/models/whisper-large-v3"
        whisper_path = cfg.get("whisper_model_path", _DEFAULT_WHISPER) or _DEFAULT_WHISPER
        if not os.path.isabs(whisper_path):
            whisper_path = resolve_path(whisper_path, _SCRIPT_DIR)
        asr_model = FrozenWhisperASR(whisper_path, device=str(device))
        asr_model = asr_model.to(device)
        if is_main:
            logger.info(f"[ASR] Whisper 已加载: {whisper_path}")
    else:
        if is_main:
            logger.info("[ASR] loss_mode=similarity，跳过 Whisper 加载")

    # ── 说话人相似度 Loss（仅 similarity / combined 模式加载）────────────
    # 使用与评估侧完全一致的双 ResNet34 编码器（en/chs）
    spk_loss_fn = None
    if loss_mode in ("similarity", "combined"):
        _DEFAULT_EN_SPK_DIR  = "/home/yuque3/nwy/real-t/spk_emb_models/voxceleb_resnet34_LM"
        _DEFAULT_CHS_SPK_DIR = "/home/yuque3/nwy/real-t/spk_emb_models/cnceleb_resnet34_LM"
        en_encoder_path  = cfg.get("spk_encoder_en_path",  _DEFAULT_EN_SPK_DIR)  or _DEFAULT_EN_SPK_DIR
        chs_encoder_path = cfg.get("spk_encoder_chs_path", _DEFAULT_CHS_SPK_DIR) or _DEFAULT_CHS_SPK_DIR
        if not os.path.isabs(en_encoder_path):
            en_encoder_path  = resolve_path(en_encoder_path,  _SCRIPT_DIR)
        if not os.path.isabs(chs_encoder_path):
            chs_encoder_path = resolve_path(chs_encoder_path, _SCRIPT_DIR)
        margin = cfg.get("sim_margin", 0.2)
        en_encoder  = FrozenSpeakerEncoder(en_encoder_path,  device=str(device)).to(device)
        chs_encoder = FrozenSpeakerEncoder(chs_encoder_path, device=str(device)).to(device)
        spk_loss_fn = SpeakerSimilarityLoss(
            en_encoder=en_encoder, chs_encoder=chs_encoder, margin=margin
        )
        if is_main:
            logger.info(
                f"[Loss] 启用说话人相似度 Ranking Loss (双编码器): "
                f"margin={margin}, en={en_encoder_path}, chs={chs_encoder_path}"
            )

    # ── 目标说话人活动检测 Loss（combined 模式且 lambda_vad > 0 时加载）──
    vad_loss_fn = None
    lambda_vad = cfg.get("lambda_vad", 0.5)
    if loss_mode == "combined" and lambda_vad > 0:
        vad_frame_shift_ms  = cfg.get("vad_frame_shift_ms", 10.0)
        vad_frame_length_ms = cfg.get("vad_frame_length_ms", 25.0)
        vad_loss_fn = TargetVADLoss(
            sample_rate=data_cfg.get("sample_rate", 16000),
            frame_shift_ms=vad_frame_shift_ms,
            frame_length_ms=vad_frame_length_ms,
        )
        if is_main:
            logger.info(
                f"[Loss] 启用目标说话人活动检测 Loss: "
                f"lambda_vad={lambda_vad}, "
                f"frame_shift={vad_frame_shift_ms}ms, "
                f"frame_length={vad_frame_length_ms}ms"
            )

    # ── 可微分 DNSMOS Loss（combined 模式且 lambda_dnsmos > 0 时加载）──────
    dnsmos_loss_fn = None
    lambda_dnsmos = cfg.get("lambda_dnsmos", 0.0)
    if loss_mode == "combined" and lambda_dnsmos > 0:
        if not _DNSMOS_LOSS_AVAILABLE:
            logger.warning(
                "[Loss] DNSMOSLoss 不可用（wesep.utils.speech_quality_losses 导入失败），"
                "跳过 DNSMOS Loss。请确认 wesep_real_tse 路径正确且 onnx2torch 已安装。"
            )
        else:
            import os as _os
            _dnsmos_dir = cfg.get("dnsmos_model_dir", None) or \
                          _os.environ.get("DNSMOS_MODEL_DIR", None) or \
                          str(_SCRIPT_DIR.parent / "REAL-TSE-Challenge" / "DNSMOS")
            _primary = str(Path(_dnsmos_dir) / "sig_bak_ovr.pt")
            _p808    = str(Path(_dnsmos_dir) / "model_v8.pt")
            _target  = cfg.get("dnsmos_target", "OVRL")
            try:
                dnsmos_loss_fn = DNSMOSLoss(
                    primary_model_path=_primary,
                    p808_model_path=_p808,
                    target_metric=_target,
                )
                dnsmos_loss_fn = dnsmos_loss_fn.to(device)
                if is_main:
                    logger.info(
                        f"[Loss] 启用可微分 DNSMOS Loss: "
                        f"target={_target}, lambda_dnsmos={lambda_dnsmos}, "
                        f"model_dir={_dnsmos_dir}"
                    )
            except Exception as e:
                logger.warning(f"[Loss] DNSMOSLoss 初始化失败，跳过: {e}")
                dnsmos_loss_fn = None

    # ── 优化器 ────────────────────────────────────────────────────────────
    opt_cfg = cfg.get("optimizer", {"lr": 1e-5, "weight_decay": 1e-5})
    optimizer = torch.optim.AdamW(
        filter(lambda p: p.requires_grad, tse_model.parameters()),
        lr           = opt_cfg.get("lr", 1e-5),
        weight_decay = opt_cfg.get("weight_decay", 1e-5),
    )
    if is_main:
        logger.info(f"优化器: AdamW, lr={opt_cfg.get('lr', 1e-5):.1e}")

    # ── 学习率调度器 ──────────────────────────────────────────────────────
    sch_cfg    = cfg.get("scheduler_args", {})
    num_epochs = cfg.get("num_epochs", 50)
    epoch_iter = max(len(dataloader), 1)

    scheduler = ExponentialDecayScheduler(
        optimizer      = optimizer,
        initial_lr     = sch_cfg.get("initial_lr", opt_cfg.get("lr", 1e-5)),
        final_lr       = sch_cfg.get("final_lr", 1e-6),
        num_epochs     = num_epochs,
        epoch_iter     = epoch_iter,
        warm_up_epoch  = sch_cfg.get("warm_up_epoch", 1),
        warm_from_zero = sch_cfg.get("warm_from_zero", False),
    )
    if is_main:
        logger.info(
            f"调度器: ExponentialDecay, "
            f"lr: {sch_cfg.get('initial_lr', 1e-5):.1e} -> {sch_cfg.get('final_lr', 1e-6):.1e}"
        )

    # ── 恢复训练 ──────────────────────────────────────────────────────────
    start_epoch = 1
    global_step = 0
    best_loss   = float("inf")

    resume_path = cfg.get("resume", None)
    if resume_path and resume_path != "null":
        resume_path = resolve_path(resume_path, _SCRIPT_DIR)
        # 取原始 module（DDP 包装前）
        raw_model = tse_model.module if world_size > 1 else tse_model
        global_step, start_epoch, best_loss = load_checkpoint(
            resume_path, raw_model, optimizer, scheduler
        )
        start_epoch = resolve_resume_epoch(start_epoch)

    cfg["_best_loss"] = best_loss
    eval_state: Dict = {}
    if is_main:
        logger.info(f"开始训练: epoch={start_epoch}..{num_epochs}, step={global_step}, world_size={world_size}")
        logger.info(
            "[Eval] epoch 后台评估已启用: "
            f"test_set={str(cfg.get('epoch_eval_test_set', 'DEV')).upper()}, "
            f"cuda={cfg.get('epoch_eval_cuda', '2')}, "
            f"fast={bool(cfg.get('epoch_eval_fast', True))}, "
            f"skip_if_running={bool(cfg.get('epoch_eval_skip_if_running', True))}"
        )

    # ── 训练循环 ──────────────────────────────────────────────────────────
    for epoch in range(start_epoch, num_epochs + 1):
        # DDP: 每 epoch 设置 sampler 的 epoch（保证打乱顺序不同）
        if sampler is not None:
            sampler.set_epoch(epoch)

        epoch_start = time.time()

        epoch_loss, global_step = train_one_epoch(
            tse_model   = tse_model,
            asr_model   = asr_model,
            dataloader  = dataloader,
            optimizer   = optimizer,
            scheduler   = scheduler,
            device      = device,
            epoch       = epoch,
            global_step = global_step,
            cfg         = cfg,
            writer      = writer if is_main else None,
            logger      = logger,
            spk_loss_fn    = spk_loss_fn,
            vad_loss_fn    = vad_loss_fn,
            dnsmos_loss_fn = dnsmos_loss_fn,
            is_main        = is_main,
            world_size  = world_size,
        )

        elapsed = time.time() - epoch_start

        if is_main:
            logger.info(
                f"[Epoch {epoch}/{num_epochs}] loss={epoch_loss:.4f} "
                f"step={global_step} time={elapsed/60:.1f}min"
            )
            if writer is not None:
                writer.add_scalar("train/epoch_loss", epoch_loss, epoch)

            # 保存 best model（仅 rank0，取 module 的 state_dict）
            raw_model = tse_model.module if world_size > 1 else tse_model
            if epoch_loss < best_loss:
                best_loss = epoch_loss
                cfg["_best_loss"] = best_loss
                best_path = model_dir / "best_checkpoint.pt"
                save_checkpoint(
                    str(best_path),
                    step=global_step,
                    epoch=epoch,
                    tse_model=raw_model,
                    optimizer=optimizer,
                    scheduler=scheduler,
                    best_loss=best_loss,
                )
                logger.info(f"[Best] epoch={epoch} loss={best_loss:.4f} -> {best_path.name}")

            save_checkpoint(
                model_dir / f"checkpoint_epoch{epoch:03d}.pt",
                step=global_step,
                epoch=epoch,
                tse_model=raw_model,
                optimizer=optimizer,
                scheduler=scheduler,
                best_loss=best_loss,
            )
            eval_state = launch_async_epoch_eval(
                epoch=epoch,
                exp_dir=exp_dir_abs,
                logger=logger,
                state=eval_state,
                cfg=cfg,
            )
        
        # 所有 rank 同步（避免慢卡影响 checkpoint 写入）
        if world_size > 1:
            dist.barrier()

    if writer is not None:
        writer.close()
    if is_main:
        logger.info("训练完成！")

    cleanup_ddp()


if __name__ == "__main__":
    main()
